# 错误、调试与测试

常见错误：
    程序编写造成，bug
    用户输入造成，可通过检查用户输入做处理
    无法在程序运行过程中预测的，也成为异常，在程序中通常是必须处理的。
调试：跟踪程序的执行，查看变量的值是否正确的过程。

## 错误处理

1. `try...except...finally`

所有错误由`BaseException`类派生，常见的错误类型和集成关系，参见[官方文档](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)
```
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```

`try...exept`可以跨越多层调用。不需要在每个可能出错的地方去捕获错误，只要在合适的层次去捕获就可以了。

2. 调用栈

出错的时候，一定要分析错误的调用栈信息，才能定位错误的位置。

3. 记录错误

内置logging模块可以非常容易的记录错误信息。
通过配置，logging还可以把错误记录到日志文件里，方便事后排查。

4. 抛出错误

因为错误是class，捕获一个错误就是捕获到该class的一个实例。因此，错误并不是凭空产生的，而是有意创建并抛出的。Python的内置函数会抛出很多类型的错误，我们自己编写的函数也可以抛出错误。

如果要抛出错误，首先根据需要，可以定义一个错误的class，选择好继承关系，然后，用raise语句抛出一个错误的实例：

只有在必要的时候才定义我们自己的错误类型。如果可以选择Python已有的内置的错误类型（比如ValueError，TypeError），尽量使用Python内置的错误类型。

raise语句如果不带参数，就会把当前错误原样抛出。此外，在except中raise一个Error，还可以把一种类型的错误转化成另一种类型：

只要是合理的转换逻辑就可以，但是，决不应该把一个IOError转换成毫不相干的ValueError

## 调试

1. print()

2. assert

```
assert n != 0, 'n is zero!'
```

运行文件可使用参数`-O`关闭断言，关闭后相当于`pass`。

3. logging

这就是`logging`的好处，它允许你指定记录信息的级别，有`debug`，`info`，`warning`，`error`等几个级别，当我们指定`level=INFO`时，`logging`.debug就不起作用了。同理，指定`level=WARNING`后，`debug`和`info`就不起作用了。这样一来，你可以放心地输出不同级别的信息，也不用删除，最后统一控制输出哪个级别的信息。

`logging`的另一个好处是通过简单的配置，一条语句可以同时输出到不同的地方，比如`console`和文件。

4. pbd

启动Python的调试器pdb，让程序以单步方式运行，可以随时查看运行状态。

```
python -m pdb .\Exercise\42.pdb.py
> f:\projects\learn-python\exercise\42.pdb.py(3)<module>()
-> s = '0'
(Pdb) l
  1     # -*- encoding : utf-8 -*-
  2
  3  -> s = '0'
  4     n = int(s)
  5     print(10 / n)
[EOF]
(Pdb) n
> exercise\42.pdb.py(4)<module>()
-> n = int(s)
(Pdb) n
> exercise\42.pdb.py(5)<module>()
-> print(10 / n)
(Pdb) n
ZeroDivisionError: division by zero
> exercise\42.pdb.py(5)<module>()
-> print(10 / n)
(Pdb) p s
'0'
(Pdb) p n
0
(Pdb)
```

5. pdb.set_trace()

这个方法也是用pdb，但是不需要单步执行，我们只需要import pdb，然后，在可能出错的地方放一个pdb.set_trace()，就可以设置一个断点。

6. IDE

## 单元测试

“测试驱动开发”（TDD：Test-Driven Development）

单元测试是用来对一个模块、一个函数或者一个类来进行正确性检验的测试工作。

以测试为驱动的开发模式最大的好处就是确保一个程序模块的行为符合我们设计的测试用例。在将来修改的时候，可以极大程度地保证该模块行为仍然是正确的。

`编写单元测试`
为了编写单元测试，我们需要引入Python自带的unittest模块
编写单元测试时，我们需要编写一个测试类，从unittest.TestCase继承。
以test开头的方法就是测试方法，不以test开头的方法不被认为是测试方法，测试的时候不会被执行。
对每一类测试都需要编写一个test_xxx()方法。由于unittest.TestCase提供了很多内置的条件判断，我们只需要调用这些方法就可以断言输出是否是我们所期望的。最常用的断言就是assertEqual()。
```
self.assertEqual(abs(-1), 1) # 断言函数返回的结果与1相等
```
另一种重要的断言就是期待抛出指定类型的Error，比如通过d['empty']访问不存在的key时，断言会抛出KeyError：
```
with self.assertRaises(KeyError):
    value = d['empty']
```
而通过d.empty访问不存在的key时，我们期待抛出AttributeError：
```
with self.assertRaises(AttributeError):
    value = d.empty
```

`运行单元测试`

最简单的运行方式是在mydict_test.py的最后加上两行代码：
```
if __name__ == '__main__':
    unittest.main()
```

这样就可以把mydict_test.py当做正常的python脚本运行：
```
$ python mydict_test.py
```

另一种方法是在命令行通过参数-m unittest直接运行单元测试：
```
$ python -m unittest mydict_test
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
```

这是推荐的做法，因为这样可以一次批量运行很多单元测试，并且，有很多工具可以自动来运行这些单元测试。

单元测试可以有效地测试某个程序模块的行为，是未来重构代码的信心保证。

单元测试的测试用例要覆盖常用的输入组合、边界条件和异常。

单元测试代码要非常简单，如果测试代码太复杂，那么测试代码本身就可能有bug。

单元测试通过了并不意味着程序就没有bug了，但是不通过程序肯定有bug。

## 文档测试

doctest非常有用，不但可以用来测试，还可以直接作为示例代码。通过某些文档生成工具，就可以自动把包含doctest的注释提取出来。用户看文档的时候，同时也看到了doctest。

```
def abs(n):
    '''
    Function to get absolute value of number.
    
    Example:
    
    >>> abs(1)
    1
    >>> abs(-1)
    1
    >>> abs(0)
    0
    '''
    return n if n >= 0 else (-n)
```

Python内置的“文档测试”（doctest）模块可以直接提取注释中的代码并执行测试。

doctest严格按照Python交互式命令行的输入和输出来判断测试结果是否正确。只有测试异常的时候，可以用...表示中间一大段烦人的输出。